#!/bin/bash

CONFIG=$HOME/.config/a2os
A2OS=/usr/lib/a2os

if [ -f $CONFIG/workdir ]; then
    WD=`cat $CONFIG/workdir`
else
    WD=$HOME/a2os
    mkdir -p $CONFIG
    echo $WD > $CONFIG/workdir
fi

if [ -d $A2OS/Linux64 ]; then
    LINUX=Linux64
else
    LINUX=Linux32
fi

if [ ! -d "$WD"/$LINUX ]; then
    mkdir -p "$WD"/$LINUX

    ln -s $A2OS/data              "$WD"/
    ln -s $A2OS/$LINUX/bin        "$WD"/$LINUX/
    cp    $A2OS/$LINUX/oberon.ini "$WD"/$LINUX/
fi

if [ ! -d "$WD"/source ]; then
    cp -r $A2OS/source            "$WD"/
fi

MSG="config: $CONFIG\\nworking directory: $WD"
echo -e "$MSG"
notify-send A2 "$MSG"

cd "$WD"/$LINUX
$A2OS/$LINUX/oberon run $A2OS/$LINUX/a2.txt
